### ISSUE TITLE
Mejoras

### ISSUE THREAD

**Issue by migueldelmazo** [Adalab/modulo-1-evaluacion-intermedia-sandra1894#1]
Muy buen trabajo @sandra1894!!!

Aquí tienes unos consejos para mejorar tu ejercicio:

Puntuación: 261 / 347
- [x] HTML > LINK: Debemos tener dos ficheros de estilos importados con un `link`.
- [x] HTML > LINK: El fichero de fuentes debe estar antes que nuestro fichero de estilos para que ningún fichero de estilos externo sobre escriba los nuestros.
- [x] HTML > HEADER: La etiqueta `img` debe tener el atributo `title`.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Blog". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: El texto del primer enlace debe ser "Contacto". Debemos ponerlo en mayúsculas con CSS.
- [x] HTML > HEADER: Los enlaces tienen que tener el atributo `title`.
- [x] HTML > MAIN: El contenido exacto del h1 debe ser "Creando diversidad digital". Debemos poner las primeras letras en mayúsculas con CSS.
- [x] CSS > ESTILOS REPETIDOS: Hay estilos repetidos en las media queries que no son necesarios, es mejor quitarlos.
- [x] CSS > FONT-FAMILY: Es recomendable que la fuente del body sea Rubik para aprovechar la herencia.
- [x] CSS > CLASES: No se deben utilizar etiquetas CSS ni ids como selectores, salvo `a`, `html` y `body`.
- [x] CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves.
- [x] CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha .

Es posible que cuando corrijas uno de estos puntos, otros se corrijan solos, ya que unos dependen de otros.

Y recuerda algo muy importante:

- Escribe tu código en inglés.
- Escribe todos los ficheros y carpetas en inglés.
- Los commits tambien tienen que ser en inglés empezando por un verbo en infinitivo.

Ánimo y si tienes cualquier duda avísame!!!

> Este issue ha sido creado automáticamente por ello puede tener algún error, si hay algo que no te enjaca dímelo cuanto antes por favor.

Por favor no cierres este issue, ya lo haremos nosotros.

**Comment by sandra1894** [comment]
Buenas Miguel, 
Ya he corregido los puntos que me indicabas en la issue, pero tengo algunas dudas.

- HTML > LINK: Debemos tener dos ficheros de estilos importados con un link. Esto no se como se hace salvo, que tenga que meter el reset dentro de mi css o que no haga falta el reset en este caso.

- CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves. Lo he comprobado, y desde el principio todas las llaves estaban cerradas, de hecho no me daba error.
 

- CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha . Esto también lo tengo como me indicas, no se que cambios tengo que hacer.

Ya me dices, muchas gracias :)

**Comment by migueldelmazo** [comment]
Hola @sandra1894, te voy contestando:

> HTML > LINK: Debemos tener dos ficheros de estilos importados con un link. Esto no se como se hace salvo, que tenga que meter el reset dentro de mi css o que no haga falta el reset en este caso.

Olvídate, este error mío.

> CSS > CLASES: El fichero CSS no es correcto. Comprueba si has cerrado todas las llaves. Lo he comprobado, y desde el principio todas las llaves estaban cerradas, de hecho no me daba error.

También es fallo mío :(

> CSS > FLEX: El HEADER en tablet debe tener los elementos alineados a izquierda y derecha . Esto también lo tengo como me indicas, no se que cambios tengo que hacer.

Pues parece que también es fallo mío...

No metas más cambios, muy buen trabajo @sandra1894 !!!
